# Generated by Django 4.0.6 on 2022-08-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['createdDate']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='createdAt',
        ),
        migrations.AddField(
            model_name='blog',
            name='createdDate',
            field=models.DateField(auto_now_add=True, default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='createdTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
