# Generated by Django 4.0.6 on 2022-08-28 02:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blogwebsite', '0002_alter_blog_options_remove_blog_createdat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['createdAt']},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='createdDate',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='createdTime',
        ),
        migrations.AddField(
            model_name='blog',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
