# Generated by Django 4.0.6 on 2022-08-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogwebsite', '0004_alter_blog_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
