# Generated by Django 4.0.6 on 2022-08-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogwebsite', '0005_alter_blog_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='createdAt',
        ),
    ]
